### ISSUE TITLE
Float inlets not working

### ISSUE THREAD

**Issue by zrhbert** [grrrwaaa/maxcpp#14]
Hi,

I've been building my own classes with this, then stumbled across the problem that my float inlets aren't working. Turns out that the float inlets aren't working for the "example" project either. Does this have something to do with a 64 Bit environment?

Max just announces: example: doesn't understand "float"

**Comment by grrrwaaa** [comment]
A fix for this just checked in. The problem was that "float" is a reserved word in C++, so the method names have to be different. The example project now demonstrates using new macros for int/float inputs as follows:

`REGISTER_INLET_FLOAT(Example, testfloat);
REGISTER_INLET_LONG(Example, testint);`
